# Generated by Django 5.1 on 2024-08-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0002_alter_post_content_alter_post_image_alter_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='recognize_image',
            field=models.ImageField(null=True, upload_to='recognize_images', verbose_name='Распознанное изображение'),
        ),
        migrations.AddField(
            model_name='post',
            name='upload_image',
            field=models.ImageField(default='default.png', upload_to='upload_images', verbose_name='Изображение для распознавания'),
        ),
    ]
