# Generated by Django 5.1 on 2024-08-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0004_post_haar_cascade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='haar_cascade',
            field=models.CharField(choices=[('haarcascade_eye.xml', 'haarcascade_eye.xml'), ('haarcascade_eye_tree_eyeglasses.xml', 'haarcascade_eye_tree_eyeglasses.xml'), ('haarcascade_frontalcatface.xml', 'haarcascade_frontalcatface.xml'), ('haarcascade_frontalcatface_extended.xml', 'haarcascade_frontalcatface_extended.xml'), ('haarcascade_frontalface_alt.xml', 'haarcascade_frontalface_alt.xml'), ('haarcascade_frontalface_alt2.xml', 'haarcascade_frontalface_alt2.xml'), ('haarcascade_frontalface_alt_tree.xml', 'haarcascade_frontalface_alt_tree.xml'), ('haarcascade_frontalface_default.xml', 'haarcascade_frontalface_default.xml'), ('haarcascade_fullbody.xml', 'haarcascade_fullbody.xml'), ('haarcascade_lefteye_2splits.xml', 'haarcascade_lefteye_2splits.xml'), ('haarcascade_license_plate_rus_16stages.xml', 'haarcascade_license_plate_rus_16stages.xml'), ('haarcascade_lowerbody.xml', 'haarcascade_lowerbody.xml'), ('haarcascade_profileface.xml', 'haarcascade_profileface.xml'), ('haarcascade_righteye_2splits.xml', 'haarcascade_righteye_2splits.xml'), ('haarcascade_russian_plate_number.xml', 'haarcascade_russian_plate_number.xml'), ('haarcascade_smile.xml', 'haarcascade_smile.xml'), ('haarcascade_upperbody.xml', 'haarcascade_upperbody.xml'), ('__init__.py', '__init__.py'), ('__init__.cpython-312.pyc', '__init__.cpython-312.pyc')], max_length=100, null=True, verbose_name='Классификатор'),
        ),
    ]
